//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_LDPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auto_LDPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ScriptSetting&gt;
        ///    &lt;Scriptes&gt;
        ///        &lt;ScriptKey&gt;
        ///            &lt;Key&gt;ClickXY&lt;/Key&gt;
        ///            &lt;Value&gt;input tap {0}&lt;/Value&gt;
        ///        &lt;/ScriptKey&gt;
        ///        &lt;ScriptKey&gt;
        ///            &lt;Key&gt;Send_key&lt;/Key&gt;
        ///            &lt;Value&gt;input keyevent {0}&lt;/Value&gt;
        ///        &lt;/ScriptKey&gt;
        ///        &lt;ScriptKey&gt;
        ///            &lt;Key&gt;Wait&lt;/Key&gt;
        ///            &lt;Value&gt;sleep {0}&lt;/Value&gt;
        ///        &lt;/ScriptKey&gt;
        ///        &lt;ScriptKey&gt;
        ///            &lt;Key&gt;Open_app&lt;/Key&gt;
        ///            &lt;Value&gt;monkey -p {0} -c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptSetting {
            get {
                return ResourceManager.GetString("ScriptSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America/New_York
        ///America/Chicago
        ///America/Denver
        ///America/Los_Angeles
        ///America/Anchorage.
        /// </summary>
        internal static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
    }
}
